routes/web.php
<?php

use App\Http\Controllers\Auth\ConfirmPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\VerificationController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');
Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
Route::get('password/confirm', [ConfirmPasswordController::class, 'showConfirmForm'])->name('password.confirm');
Route::post('password/confirm', [ConfirmPasswordController::class, 'confirm']);
Route::get('email/verify', [VerificationController::class, 'show'])->name('verification.notice');
Route::get('email/verify/{id}/{hash}', [VerificationController::class, 'verify'])->name('verification.verify');
Route::get('email/resend', [VerificationController::class, 'resend'])->name('verification.resend');

Route::middleware(
    [
        'auth:web'
    ]
)->group(
    static function () {
        Route::get('home', [HomeController::class, 'index'])->name('home');

        Route::prefix('users')->as('users.')->group(
            static function () {
                Route::get('', [UserController::class, 'index'])
                    ->name('index');
                Route::get('/search', [UserController::class, 'search'])
                    ->name('search');
                Route::get('/create', [UserController::class, 'create'])
                    ->name('create');
                Route::post('/store', [UserController::class, 'store'])
                    ->name('store');
                Route::get('/{user}/edit', [UserController::class, 'edit'])
                    ->name('edit')
                    ->where('user', '[0-9]+');
                Route::put('{user}/update', [UserController::class, 'update'])
                    ->name('update')
                    ->where('user', '[0-9]+');
                Route::get('/{user}/delete', [UserController::class, 'delete'])
                    ->name('delete')
                    ->where('user', '[0-9]+');
            }
        );
    });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    public const TABLE = 'users';
    public const FIELD_ID = 'id';
    public const FIELD_NAME = 'name';
    public const FIELD_EMAIL = 'email';
    public const FIELD_PASSWORD = 'password';

    public const KEY_ORDER_BY = 'orderBy';
    public const KEY_DIRECTION = 'direction';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        self::FIELD_NAME,
        self::FIELD_EMAIL,
        self::FIELD_PASSWORD,
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return string
     */
    public function getEmail(): string
    {
        return $this->getAttribute(self::FIELD_EMAIL);
    }

    /**
     * @param string $password
     */
    public function setPasswordAttribute(string $password): void
    {
        $this->attributes['password'] = Hash::make($password);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use Exception;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class UserController extends Controller
{
    private const DEFAULT_RESULTS_PER_PAGE = 20;

    /**
     * @param Request $request
     * @return View
     */
    public function index(Request $request): View
    {
        $users = User::query()
            ->orderBy(
                $request->get(User::KEY_ORDER_BY) ?? User::FIELD_ID,
                $request->get(User::KEY_DIRECTION) ?? 'asc'
            )
            ->simplePaginate(self::DEFAULT_RESULTS_PER_PAGE);

        return view('users.index', ['users' => $users]);
    }

    /**
     * @param Request $request
     * @return View
     */
    public function search(Request $request): View
    {
        $query = $request->get(User::FIELD_EMAIL);
        $users = User::query()
            ->where(User::FIELD_EMAIL, 'LIKE', "%{$query}%")
            ->simplePaginate(self::DEFAULT_RESULTS_PER_PAGE);

        return view(
            'users.index',
            [
                'users' => $users,
                'query' => $query
            ]
        );
    }

    /**
     * @return View
     */
    public function create(): View
    {
        return view('users.create');
    }

    /**
     * @param UserStoreRequest $request
     * @return RedirectResponse
     */
    public function store(UserStoreRequest $request): RedirectResponse
    {
        $user = User::create($request->validated());
        event(new Registered($user));

        return redirect()->route('users.index')->withSuccess(__('dashboard.success'));
    }

    /**
     * @param User $user
     * @return View
     */
    public function edit(User $user): View
    {
        return view('users.edit', [
            'user' => $user
        ]);
    }

    /**
     * @param UserUpdateRequest $request
     * @param User $user
     * @return RedirectResponse
     */
    public function update(UserUpdateRequest $request, User $user): RedirectResponse
    {
        $user->update($request->validated());

        return redirect()->route('users.index')->withSuccess(__('dashboard.success'));
    }

    /**
     * @param User $user
     * @return RedirectResponse
     * @throws Exception
     */
    public function delete(User $user): RedirectResponse
    {
        $user->delete();

        return redirect()->route('users.index')->withSuccess(__('dashboard.success'));
    }

}

resources/views/error.blade.php
@extends('layouts.app')

@section('content')

    <section class="no-padding-top no-padding-bottom">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 badge-danger p-5">
                    <h3>{{ __('dashboard.errors_occurs') }}</h3>
                    <div>
                        @if ($errors->any())
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif
                    </div>
                </div>

            </div>
        </div>
    </section>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

    <section class="no-padding-top no-padding-bottom">
        <div class="container-fluid">
            <div class="row">

                <div class="col-lg-12 mt-3 mb-3">
                    <div class="block">
                        <h1>{{ __('dashboard.home.title') }} : {{ config('app.name') }}</h1>
                    </div>
                    <hr>
                </div>

                <div class="col-lg-12">
                    <div class="block">
                        <a class="btn btn-outline-info"
                           href="{{ route('users.index') }}">
                            {{ __('dashboard.users.title') }}
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </section>

@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name') }}</title>
    @include('layouts.styles.header_styles')
    @include('layouts.scripts.header_scripts')
</head>
<body class="sb-nav-fixed" onbeforeunload="return showLoader()">
    @include('layouts.sections.success')
    @include('layouts.menu_up')
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            @include('layouts.menu')
        </div>
        <div id="layoutSidenav_content">
            <div id="loader" class="badge m-3 d-none">
                <img decoding="async" src="{{ asset('img/loader.gif') }}" alt="loader">
            </div>
            <main id="data_results">
                @yield('content')
            </main>
        </div>
    </div>
    @include('layouts.scripts.footer_scripts')
</body>
</html>

resources/views/layouts/menu.blade.php
<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <div class="sb-sidenav-menu-heading">{{ __('dashboard.menu') }}</div>
            <a class="nav-link" href="{{ route('users.index') }}">
                <div class="sb-nav-link-icon">
                    <i class="fa fa-user"></i>
                </div>
                {{ __('dashboard.users.title') }}
            </a>
        </div>
    </div>
</nav>

resources/views/layouts/menu_up.blade.php
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ route('login') }}">
    {{ config('app.name') }}
    </a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle"><i
            class="fa fa-bars"></i></button
    ><!-- Navbar Search-->
    <div class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="small text-white">
           {{ \Illuminate\Support\Facades\Auth::user()->name }}
            <br><small>
                {{ \Illuminate\Support\Facades\Auth::user()->email }}
            </small></div>
    </div>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fa fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    [ test item ]
                </a>
                <div class="dropdown-divider"></div>
                <a id="logout" class="dropdown-item" href="{{ route('logout') }}"
                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();"> <span
                        class="d-none d-sm-inline">{{ __('dashboard.logout') }}</span>
                    <i class="icon-logout"></i>
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/scripts/footer_scripts.blade.php
<script type="text/javascript" src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/scripts.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/lazy_load_photos.js') }}"></script>

<script type="text/javascript">
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })

    function showLoader() {
        $('#loader').removeClass('d-none');
        $('#data_results').addClass('d-none');
    }
</script>

resources/views/layouts/scripts/header_scripts.blade.php
<script type="text/javascript" src="{{ asset('js/jquery-3.4.1.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/jquery-ui.js') }}"></script>
<script type="text/javascript" src="{{ asset('dropzone/dist/min/dropzone.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/select2.min.js') }}"></script>

resources/views/layouts/sections/success.blade.php
@if (isset($success) || session('success') || session('status') || (isset($errors) && $errors->any()) || (string)request()->old('success') !== '')
    @if ((isset($success) && $success === true) || (session()->has('success') && session()->get('success') === true))
        <div class="fadeInDown col-12 success_modal bg-success p-4" style="position: fixed;z-index:100000000;">
            <div class="user-block block text-center badge-success">
                <h3>{{ __('dashboard.success') }}</h3>
            </div>
        </div>
    @elseif((string)request()->old('success') !== '')
        <div class="fadeInDown col-12 success_modal bg-success p-4" style="position: fixed;z-index:100000000;">
            <div class="user-block block text-center badge-success">
                <h3>{{ __('dashboard.success') }}</h3>
                <p>{{ request()->old('success') }}</p>
            </div>
        </div>
    @elseif(session('status') || session('success'))
        <div class="fadeInDown col-12 success_modal bg-success p-4" style="position: fixed;z-index:100000000;">
            <div class="user-block block text-center badge-success">
                <h3>{{ __('dashboard.success') }}</h3>
            </div>
        </div>
    @elseif((isset($success) && $success === false) || $errors->any())
        <div class="fadeInDown col-12 success_modal bg-danger p-4" style="position: fixed;z-index:100000000;">
            <div class="user-block block text-center badge-danger">
                @if(isset($errors))
                    <h3>
                        {{ __('dashboard.errors') }}
                    </h3>
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                @else
                    <h3>{{ __('dashboard.errors') }}</h3>
                @endif
            </div>
        </div>
    @else
        <div class="fadeInDown col-12 success_modal bg-info p-4" style="position: fixed;z-index:100000000;">
            <div class="user-block block text-center badge-info">
                <h3>{{ $success }}</h3>
            </div>
        </div>
    @endif
    <script>
        window.setTimeout(function () {
            $(".success_modal").fadeTo(500, 0).slideUp(500, function () {
                $(this).remove();
            });
        }, 1500);
    </script>
@endif

resources/views/layouts/styles/header_styles.blade.php
<link href="{{ asset('css/styles.css') }}" rel="stylesheet">
<link href="{{ asset('css/font-awesome.css') }}" rel="stylesheet">
<link href="{{ asset('css/jquery-ui.css') }}" rel="stylesheet">
<link href="{{ asset('dropzone/dist/min/dropzone.min.css') }}" rel="stylesheet">
<link href="{{ asset('css/select2.min.css') }}" rel="stylesheet">
<link href="{{ asset('css/ekko-lightbox.css') }}" rel="stylesheet">

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')

    <section class="no-padding-bottom">
        <div class="container-fluid">
            <div class="row">

                <div class="col-lg-12 mt-3 mb-3">
                    <div class="block">
                        <h1>{{ __('dashboard.users.add') }}</h1>
                    </div>
                    <hr>
                </div>

                <div class="col-lg-10">
                    <div class="user-block block text-center">

                        <form method="POST" action="{{ route('users.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">{{ __('dashboard.users.name') }}</label>
                                <div class="col-sm-9">
                                    <input name="name"
                                           type="text"
                                           class="form-control{!! (isset($errors) && $errors->first('name')) ? ' is-invalid' : '' !!}"
                                           value="{{ old('name') }}">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">{{ __('dashboard.users.email') }}</label>
                                <div class="col-sm-9">
                                    <input name="email"
                                           type="text"
                                           class="form-control{!! (isset($errors) && $errors->first('email')) ? ' is-invalid' : '' !!}"
                                           value="{{ old('email') }}">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">{{ __('dashboard.users.password') }}</label>
                                <div class="col-sm-9">
                                    <input name="password"
                                           type="password"
                                           class="form-control{!! (isset($errors) && $errors->first('password')) ? ' is-invalid' : '' !!}"
                                           value="{{ old('password') }}">
                                </div>
                            </div>

                                <div class="col-sm-9 offset-3 mt-2 mb-4">
                                    <button type="submit"
                                            class="btn btn-lg btn-outline-success btn-block">
                                        {{ __('dashboard.save') }}
                                    </button>
                                </div>

                        </form>

                    </div>
                </div>

                <div class="col-lg-12">
                    <hr>
                    <div class="block">
                        <a class="btn btn-outline-danger"
                           href="{{ route('users.index') }}">
                            {{ __('dashboard.back_to') }} {{ __('dashboard.users.title') }}
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </section>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')

    <section class="no-padding-bottom">
        <div class="container-fluid">
            <div class="row">

                <div class="col-lg-12 mt-3 mb-3">
                    <div class="block">
                        <h1>{{ __('dashboard.users.edit') }}</h1>
                    </div>
                    <hr>
                </div>

                <div class="col-lg-10">
                    <div class="user-block block text-center">

                        <form method="POST" action="{{ route('users.update', $user->id) }}">
                            @csrf
                            @method('PUT')

                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">{{ __('dashboard.users.name') }}</label>
                                <div class="col-sm-9">
                                    <input name="name"
                                           type="text"
                                           class="form-control{!! (isset($errors) && $errors->first('name')) ? ' is-invalid' : '' !!}"
                                           value="{{ old('name') ?: $user->name }}">
                                </div>
                            </div>

                            <div class="line"></div>

                            <div class="col-sm-9 offset-3 mt-2 mb-4">
                                <button type="submit"
                                        class="btn btn-lg btn-outline-success btn-block">
                                    {{ __('dashboard.save') }}
                                </button>
                            </div>

                        </form>

                    </div>
                </div>

                <div class="col-lg-12">
                    <hr>
                    <div class="block">
                        <a class="btn btn-outline-danger"
                           href="{{ route('users.index') }}">
                            {{ __('dashboard.back_to') }} {{ __('dashboard.users.title') }}
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </section>

@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')

    <section class="no-padding-top">
        <div class="container-fluid">
            <div class="row">

                <div class="col-lg-12 mt-3 mb-3">
                    <div class="block">
                        <h1>{{ __('dashboard.users.title') }}
                            <a class="btn btn-outline-secondary btn-sm" href="{{ route('users.create') }}">
                                {{ __('dashboard.users.add') }}</a>
                        </h1>

                    </div>
                </div>

                <div class="col-lg-12 badge-light pt-2">
                    <div class="block">
                        <form action="{{route('users.search')}}">
                            @csrf
                            <div class="form-group row">
                                <span class="col-sm-2 mt-2">
                                    <label for="{{ \App\Models\User::FIELD_EMAIL }}"
                                            class="form-control-label">
                                        {{__('dashboard.users.search')}}
                                    </label>
                                </span>
                                <span class="col-sm-4 mt-2">
                                    <input class="form-control"
                                           type="search"
                                           id="{{ \App\Models\User::FIELD_EMAIL }}"
                                           name="{{ \App\Models\User::FIELD_EMAIL }}"
                                           placeholder="{{ __('dashboard.users.email_search_placeholder') }}"
                                           value="{{ $query ?? '' }}"/>
                                </span>
                                <span class="col-sm-4 mt-2">
                                    <input
                                            class="btn btn-outline-info"
                                            type="submit" value="{{__('dashboard.users.search')}}"
                                    />
                                </span>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-lg-12 mb-3 mt-4">
                    <div class="text-center">
                        {{ $users->links() }}
                    </div>
                </div>

                <div class="col-lg-12">
                    <div class="block">
                        @if(isset($query))
                            <p class="text-gray-light">
                                {{ __('dashboard.results_for') }} : {{ $query }}
                            </p>
                            <hr>
                        @endif
                        <div class="table-responsive">
                            <table class="table table-striped table-sm text-gray-light">
                                <thead>
                                <tr>
                                    <th style="min-width: 50px;">
                                        @if(!isset($query))
                                            <span>
                                            <a href="{{route('users.index',
                                            [
                                            \App\Models\User::KEY_ORDER_BY => 'id',
                                            \App\Models\User::KEY_DIRECTION => 'asc'
                                            ])}}">
                                                <i class="fa fa-sort-numeric-up-alt"></i>
                                            </a>
                                        </span>
                                            <span>
                                            <a href="{{route('users.index',
                                            [
                                            \App\Models\User::KEY_ORDER_BY => 'id',
                                            \App\Models\User::KEY_DIRECTION => 'desc'
                                            ])}}">
                                                <i class="fa fa-sort-numeric-down-alt"></i>
                                            </a>
                                        </span>
                                            <br>
                                        @endif
                                        {{__('dashboard.id')}}
                                    </th>
                                    <th>{{ __('dashboard.users.name') }}</th>
                                    <th>{{ __('dashboard.users.email') }}</th>
                                    <th>{{ __('dashboard.users.action') }}</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($users as $user)
                                    <tr>
                                        <th scope="row">{{ $user->id }}</th>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>
                                            <a href="{{ route('users.edit', $user->id) }}">
                                                <i class="fa fa-edit text-info"></i>
                                            </a>
                                            <a href="{{ route('users.delete', $user->id) }}"
                                               data-toggle="tooltip" data-placement="left"
                                               title="{{ __('dashboard.users.delete') }}"
                                               onclick="return confirm('{{ __('dashboard.confirm_action') }}')"
                                            >
                                                <i class="fa fa-times text-danger"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12 mb-5">
                    <hr>
                    <div class="pt-2 text-center">
                        {{ $users->links() }}
                    </div>
                </div>

            </div>
        </div>
    </section>

@endsection